import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar />

			<h1 className='text-3xl font-light bg-red-400'>This is my portfolio</h1>
		</div>
	);
}
