import Head from "next/head";
import Home from "../components/Home";
import Navbar from "../components/Navbar";

export default function Startup() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar />
			<Home />
		</div>
	);
}
